FROM node:20-alpine

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

ENV NEXT_PUBLIC_BASE_API=http://quotes-api-balancer-1983918120.eu-north-1.elb.amazonaws.com

RUN npm run build


EXPOSE 80

CMD ["npm", "run", "start"]



