FROM node:20-alpine

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

RUN chmod u+x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"] 

EXPOSE 80

CMD ["npm", "run", "start"]



