version: '3.9'

services:
  client:
    build: ./client
    container_name: quotes_client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - api
      
  api:
    build: ./api
    container_name: quotes_api
    env_file:
      - ./api/.env
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    image: postgres
    container_name: quotes_db
    restart: always
    hostname: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./env/db.env