// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: authors.sql

package database

import (
	"context"
)

const createAuthor = `-- name: CreateAuthor :exec
insert into authors (name) values ($1)
`

func (q *Queries) CreateAuthor(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createAuthor, name)
	return err
}

const fetchAuthors = `-- name: FetchAuthors :many
select id, name from authors
`

func (q *Queries) FetchAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, fetchAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
