// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Author struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Quote struct {
	ID       int32  `json:"id"`
	Text     string `json:"text"`
	AuthorID int32  `json:"author_id"`
}
